[project]
name = "dog_safe_rekognition"
version = "0.1.0"
description = "Upload photo of ingredient list to see if safe for dogs"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.42.33",
    "streamlit>=1.53.1",
]

[dependency-groups]
dev = [
    "types-boto3[bedrock,bedrock-runtime,essential,rekognition]>=1.42.33",
]
